[tool.poetry]
name = "replacer"
version = "0.1.0"
description = ""
authors = ["Kota Hashihama <kotahashihama@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.0.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
